name: Integration

on:
  push:
    branches:
      - "develop"
  pull_request:
  repository_dispatch:
    types: [alfalfa-update]

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v4.0.0
        with:
          poetry-version: "2.1.1"

      - name: Start Alfalfa
        uses: NatLabRockies/alfalfa-action@v1
        with:
          tag: "pacer-dev-prod-docs"
          compose-file-ref: "pacer-dev-prod-docs"
          worker-scale: 2

      - name: Wait for web API
        uses: iFaxity/wait-on-action@v1.2.1
        with:
          resource: http://localhost

      - name: Run tests with poetry and pytest
        run: |
          poetry install
          poetry run pytest -m integration
